# This is the workflow for daily reminds.

name: DailyReminder

# Controls when the workflow will run
on:
  # Triggers the workflow on a schedule
  schedule:
    - cron: '46 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Runs the remind python script using the runners shell
      - name: Run a one-line script
        run: python ./remind.py --send-key ${{ secrets.SEND_KEY_ZQZ }} --time-zone ${{ secrets.TIME_ZONE_ZQZ }}
