# This is the workflow for daily reminds.

name: DailyReporterZQZ

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      # Runs the report python script using the runners shell
      - name: Install dependencies and run script
        run: |
          pip install -r requirements.txt
          python ./report.py --send-key ${{ secrets.SEND_KEY_ZQZ }} --weather-key ${{ secrets.WEATHER_KEY }} --alpha-vantage-key ${{ secrets.ALPHA_VANTAGE_KEY }} --time-zone ${{ secrets.TIME_ZONE_ZQZ }} --weather-location ${{ secrets.WEATHER_LOCATION_ZQZ }}
